project_name: procguard
version: 2

builds:
  - id: ProcGuard
    binary: ProcGuard
    skip: true
    targets:
      - windows_amd64_v1
    hooks:
      pre:
        - dir: wails-app
          cmd: make build VERSION={{.Version}}

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Ext }}"
    files:
      - src: 'wails-app/build/bin/ProcGuard.exe'
        dst: ProcGuard.exe

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: infraflakes
    name: procguard

